import {randomBytes} from "node:crypto";
import type {FastifyInstance} from "fastify";

export function registerLiveTestAdminPage(app: FastifyInstance): void {
  app.get("/internal/admin/live-tests", async (_request, reply) => {
    const nonce = randomBytes(18).toString("base64");
    reply.header("cache-control", "no-store").header("referrer-policy", "no-referrer")
      .header("content-security-policy", "default-src 'none'; script-src 'nonce-" + nonce + "'; style-src 'nonce-" + nonce + "'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'");
    return reply.type("text/html; charset=utf-8").send(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quefa 实单联调</title>
<style nonce="${nonce}">:root{font-family:"Microsoft YaHei","PingFang SC",sans-serif;color:#182e49;background:#f2f6fb}*{box-sizing:border-box}body{margin:0;padding:32px 16px}main{max-width:880px;margin:auto;background:#fff;padding:32px;border-top:4px solid #1764c0}h1{font-size:26px}h2{font-size:16px;overflow-wrap:anywhere}p{line-height:1.8}input{display:block;width:100%;max-width:580px;margin:12px 0;padding:12px;font:inherit;border:1px solid #52677d;border-radius:4px}button{font:inherit;padding:10px 16px;background:#1764c0;color:#fff;border:0;border-radius:4px;cursor:pointer;margin:8px 8px 8px 0}button:disabled{opacity:.5;cursor:default}.cancel{background:#fff;color:#1764c0;border:1px solid #1764c0}.approve{background:#9e391b}article{border-top:1px solid #d8e3ef;padding:20px 0}.muted{color:#52677d}#output{white-space:pre-wrap;overflow-wrap:anywhere}:focus-visible{outline:3px solid #182e49;outline-offset:4px}@media(max-width:500px){main{padding:20px}}</style>
<main><h1>Quefa 实单联调</h1><p>这里操作的是实际付款订单。批准充值可能立即扣取供应账户余额；仅验证本地提交时，请取消待派发任务。</p>
<label for="token">平台管理令牌</label><input id="token" type="password" autocomplete="off" spellcheck="false"><button id="load">读取联调订单</button>
<p class="muted">令牌只在本页使用，不写入浏览器存储。停用兑换码不代表服务费或支付宝款项已退款。</p>
<p id="output" role="status" aria-live="polite">输入令牌后读取订单。</p><section id="orders" aria-label="联调订单"></section></main>
<script nonce="${nonce}">const $=id=>document.getElementById(id);const base='/internal/admin/api/supply/test-orders';async function request(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'x-platform-admin-token':$('token').value,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||'请求失败，请重试');return d}function text(parent,tag,value){const e=document.createElement(tag);e.textContent=value;parent.append(e);return e}function button(parent,label,path,body,prompt,style){const b=text(parent,'button',label);b.className=style||'';b.onclick=async()=>{if(!confirm(prompt))return;b.disabled=true;try{await request(path,body);await load();$('output').textContent='操作已受理，请核对最新状态。'}catch(e){$('output').textContent=e.message}finally{b.disabled=false}}}async function load(){$('load').disabled=true;try{const d=await request(base);$('orders').replaceChildren();$('output').textContent=d.data.length?'已读取 '+d.data.length+' 笔联调订单。':'暂无联调订单。';for(const order of d.data){const card=document.createElement('article');$('orders').append(card);text(card,'h2',order.order_id);text(card,'p','付款：'+order.payment_status+'；兑换码：'+(order.voucher_status||'未签发'));const root=base+'/'+encodeURIComponent(order.order_id);if(['unused','disabling'].includes(order.voucher_status)){button(card,order.voucher_status==='disabling'?'重试确认停码':'停用未兑换 CDK',root+'/disable-cdk',{confirm_disable:true},'确认停用这张兑换码？此操作不会自动退款。','cancel')}for(const task of order.fulfillments){text(card,'p',task.fulfillment_id+'：'+(task.message||task.status));if(task.status==='queued'){if(!task.submission_approved)button(card,'批准真实充值',root+'/fulfillments/'+encodeURIComponent(task.fulfillment_id)+'/approve',{acknowledge_real_charge:true},'确认提交这笔真实充值？上游可能立即扣费执行，不能保证取消。','approve');else text(card,'p','已批准，后台任务可能随时派发。');button(card,'取消尚未派发任务',root+'/fulfillments/'+encodeURIComponent(task.fulfillment_id)+'/cancel',{confirm_cancel:true},'确认取消尚未派发的任务？已开始派发时会拒绝取消。','cancel')}}}}catch(e){$('output').textContent=e.message}finally{$('load').disabled=false}}$('load').onclick=load;</script></html>`);
  });
}
