import {runInNewContext} from "node:vm";
import {describe,expect,it,vi} from "vitest";
import {workspaceJs} from "../src/operations/workspace-page.js";
function harness(fetcher:typeof fetch){const context:{hooks?:any;[key:string]:unknown}={fetch:fetcher,AbortController,setTimeout,clearTimeout,URL,URLSearchParams,location:{origin:"https://tibo.test",hostname:"tibo.test",protocol:"https:",search:""},document:{querySelector:()=>null,addEventListener:()=>{}},window:{addEventListener:()=>{}},localStorage:{getItem:()=>null}};
  runInNewContext(workspaceJs.split("\napplyEntryQuery();")[0]+"\nglobalThis.hooks={api,cache:responseCache,inflight,identity:(id,tenant)=>{me={id,role:'agent_owner'};merchant=tenant;},detailNeedsLiveSync,detailProgressState};",context);return context.hooks!;}
const response=(value:unknown)=>({ok:true,status:200,text:async()=>JSON.stringify(value)}) as Response;
describe("workspace request and progress plumbing",()=>{
  it("deduplicates live reads and does not let one aborted view cancel the other reader",async()=>{let resolve!:(v:Response)=>void;const fetcher=vi.fn(()=>new Promise<Response>(r=>resolve=r)),h=harness(fetcher as typeof fetch);h.identity("a","m1");const controller=new AbortController(),first=h.api("/orders","GET",undefined,{signal:controller.signal}),rejected=expect(first).rejects.toMatchObject({name:"AbortError"}),second=h.api("/orders");controller.abort();await rejected;const third=h.api("/orders");expect(fetcher).toHaveBeenCalledTimes(1);resolve(response({data:[]}));await Promise.all([second,third]);expect(h.inflight.size).toBe(0);});
  it("retains metadata after a GET, invalidates after writes, and isolates cache by identity and tenant",async()=>{const fetcher=vi.fn(async()=>response({data:[]})),h=harness(fetcher as typeof fetch);h.identity("a","m1");await h.api("/agents");await h.api("/orders");await h.api("/agents");expect(fetcher).toHaveBeenCalledTimes(2);h.identity("a","m2");await h.api("/agents");h.identity("b","m2");await h.api("/agents");expect(fetcher).toHaveBeenCalledTimes(4);await h.api("/agents","PUT",{});await h.api("/agents");expect(fetcher).toHaveBeenCalledTimes(6);});
  it("does not repopulate stale cache after an intervening write",async()=>{let resolve!:(v:Response)=>void;const fetcher=vi.fn((url:string)=>url.endsWith("/agents")?new Promise<Response>(r=>resolve=r):Promise.resolve(response({}))),h=harness(fetcher as typeof fetch);const p=h.api("/agents");await h.api("/products/x","PUT",{});resolve(response({data:["stale"]}));await p;expect(h.cache.size).toBe(0);});
  it("keeps terminal dialogs quiet but refreshes pending payment and in-flight recharge",()=>{const h=harness(vi.fn() as unknown as typeof fetch);expect(h.detailNeedsLiveSync({paymentStatus:"pending"})).toBe(true);expect(h.detailNeedsLiveSync({paymentStatus:"paid",timeline:{fulfillmentStatus:"running"}})).toBe(true);expect(h.detailNeedsLiveSync({paymentStatus:"paid",deliveryMode:"cdk",voucherCode:"test",timeline:{fulfillmentStatus:"succeeded"}})).toBe(false);});
  it("never marks a queued or running recharge as completed and shows the published stage",()=>{const h=harness(vi.fn() as unknown as typeof fetch);expect(h.detailProgressState({timeline:{fulfillmentStatus:"queued"},fulfillment:{progress_stage:"queued"}})).toMatchObject({done:false,failed:false,label:"排队中"});expect(h.detailProgressState({timeline:{fulfillmentStatus:"running"},fulfillment:{progress_stage:"logging_in"}})).toMatchObject({done:false,label:"正在登录"});expect(h.detailProgressState({timeline:{fulfillmentStatus:"failed"},fulfillment:{progress_stage:"failed"}})).toMatchObject({done:true,failed:true,label:"充值失败"});});
  it("uses shared native dialogs and lazy payment configuration rather than blocking native prompts",()=>{expect(workspaceJs).not.toMatch(/\b(?:prompt|confirm)\(/);expect(workspaceJs).toContain('function confirmAction(');expect(workspaceJs).toContain('button("配置与启用"');expect(workspaceJs).toContain('按上游订单查美元成本');});
  it("keeps orders refreshable without replacing current content",()=>{expect(workspaceJs).toContain('button("刷新订单"');expect(workspaceJs).toContain('保留当前订单');expect(workspaceJs).toContain('orders?.some(orderNeedsLiveSync)?3000:30000');expect(workspaceJs).toContain('window.addEventListener("online"');});
  it("uses four-character role navigation with shareable browser history",()=>{expect(workspaceJs).toContain('["overview","平台总览"');expect(workspaceJs).toContain('["notifications","待办中心"');expect(workspaceJs).toContain('["apiAccess","开放接口"');expect(workspaceJs).toContain('["overview","业务总览"');expect(workspaceJs).toContain('function viewHref(name)');expect(workspaceJs).toContain('window.addEventListener("popstate"');expect(workspaceJs).toContain('aria-current');});
  it("opens order details in the responsive workspace drawer and exposes refunded orders",()=>{expect(workspaceJs).toContain('workspace-modal workspace-drawer order-detail-modal');expect(workspaceJs).toContain('["refunded","已退款"]');expect(workspaceJs).toContain('class:"orders-surface"');});
});
