\set ON_ERROR_STOP on

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO quefa_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO quefa_app;

-- 应用账号不是表所有者、超级用户或 BYPASSRLS 角色，必须经过 RLS。
ALTER ROLE quefa_app NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;

-- owner 仅用于迁移和备份；运行时绝不使用此账号。
ALTER ROLE quefa_owner NOBYPASSRLS;
