/** Shared native dialogs and finance views. Escapes via existing DOM text helpers. */
export const financeWorkspaceJs = String.raw`
function confirmAction(message){return new Promise(resolve=>{const focus=document.activeElement,dialog=el("dialog",{class:"workspace-modal decision-modal","aria-label":"确认操作"});let done=false;const finish=value=>{if(done)return;done=true;resolve(value);dialog.close();};dialog.append(el("div",{class:"modal-shell"},el("header",{class:"modal-head"},el("h2",{},"确认操作"),button("关闭",()=>finish(false))),el("div",{class:"modal-body"},el("p",{class:"decision-copy"},message),el("div",{class:"actions"},button("取消",()=>finish(false)),button("确认执行",()=>finish(true),"primary")))));dialog.addEventListener("cancel",()=>finish(false));dialog.addEventListener("close",()=>{if(!done){done=true;resolve(false);}dialog.remove();focus?.isConnected&&focus.focus();},{once:true});document.body.append(dialog);dialog.showModal();});}
function askText(message,value=""){return new Promise(resolve=>{let answered=false;const dialog=openFormModal(message,[input("answer",message,"textarea",value,{maxlength:1000,rows:3})],"继续",d=>{answered=true;resolve(d.answer);});dialog.addEventListener("close",()=>{if(!answered)resolve(null);},{once:true});});}
function moneyField(name,label,value=""){return input(name,label,"number",value??"",{min:"0",step:"0.01",required:["standardUsd","actualUsd","feesUsd","retainedUsd","retainedFeeUsd","usd","amount"].includes(name)});}
function financialRows(items){return el("dl",{class:"financial-rows"},items.map(([label,value])=>[el("dt",{},label),el("dd",{},value==null?"待核算":value)]));}
const costStatusLabel={pending_review:"待核验",confirmed:"成本已确认",disputed:"成本异常 · 待核查",pending_payment:"待支付",partially_paid:"部分支付",paid:"已支付",not_required:"无需补差",suspended_refund:"订单已退款 · 补差暂停"};
function costLabel(v){return costStatusLabel[v]||word(v);}
function costDestination(v){return v==="customer_direct"?"直接退客户":v==="platform_pass_through"?"退代理代退客户":"尚未选择";}
function costFinancePanels(view){const c=view.costAccounting||{},agent=view.collectionMode==="agent_collect",commission=orderDetailPanel(agent?"采购与交付":"代理分佣",financialRows([[agent?"冻结采购价":"冻结供货价","¥"+view.supplyAmount],["客户付款 / 采购款","¥"+view.saleAmount],["普通退款","¥"+view.ordinaryRefunded],["平台承担差价","¥"+view.priceAdjustmentRefunded],["代理分佣",agent?"自收款：零售利润由代理自行核算":"¥"+view.margin]]),true);
  if(!platform())return [commission,orderDetailPanel("补差处理",costReceiptContent(view),false)];
  const costBody=el("div",{},financialRows([["核验状态",costLabel(c.status)],["冻结退差基准 USD",(c.refundBenchmarkUsd??c.standardUsd)],["原币最终金额",c.nativeAmountMinor==null?"尚未核对":c.nativeCurrency+" "+(c.nativeAmountMinor/100).toFixed(2)],["上游匹配美元 USD",c.tradeCandidate?.usd],["美元交易证据",c.tradeCandidate?c.tradeCandidate.state==="settled"?"清算完成":"授权记录投影 · 待确认清算":c.tradeMatchIssue==="ambiguous_trades"?"同卡多笔匹配，待人工核对":"尚未关联"],["已核实成本 USD",c.actualUsd],["独立实际费用 USD",c.additionalFeesUsd],["毛节省 USD",c.grossSavingUsd],["约定保留 USD",c.retainedFeeUsd],["我方毛利 CNY",c.grossProfitCny]]),el("p",{class:"muted"},"退差基准只用于判断补差，不代表实际成本。原币报价不等于美元清算成本。缺少真实关联凭证或汇率时保留待核算；保留费用不重复计入实际成本。"));
  if(can("wallet.review"))costBody.append(el("div",{class:"actions"},button("按上游订单查美元成本",async()=>{await api("/orders/"+id(view.id)+"/cost/sync","POST",{});await refreshOpenOrder(view.id);}),button("核实成本与补差",()=>openCostVerification(view),"primary")));
  const rebate=el("div",{},financialRows([["补差状态",costLabel(c.payoutState)],["付款去向",costDestination(c.destination)],["净应补差 USD",c.refundDueUsd],["已付 USD",c.paidUsd],["剩余 USD",c.remainingUsd]]),el("p",{class:"muted"},"客户补差另行处理，不减少代理基础分佣。退代理代退不代表客户已收到；两条路径不可重复执行。"));
  if(can("wallet.review")&&c.status==="confirmed"&&c.destination&&Number(c.remainingUsd)>0)rebate.append(button("登记已实际支付",()=>openCostPayment(view),"primary"));
  rebate.append(costReceiptContent(view));if(c.payments?.length)rebate.append(table(["日期","金额","方式","流水"],c.payments.map(p=>[date(p.createdAt),p.currency+" "+p.amount,p.method,p.reference])));
  return [commission,orderDetailPanel("成本核算",costBody,true),orderDetailPanel("补差退款",rebate,true)];
}
function costReceiptContent(view){const c=view.costAccounting||{},body=el("div",{},financialRows([["处理状态",costLabel(c.payoutState)],["去向",costDestination(c.destination)],["应补差 USD",c.refundDueUsd],["已付 USD",c.paidUsd],["客户已收到",c.customerReceipt==="confirmed"?"已确认":"尚未确认"]]));if(c.destination==="platform_pass_through"&&c.payoutState==="paid"&&c.customerReceipt!=="confirmed"&&can("wallet.read"))body.append(button("确认客户已收到补差",()=>openFormModal("确认客户补差已到账",[input("evidence","客户实际收款凭证说明","textarea","",{required:true,minlength:6,maxlength:1000})],"确认客户已收到",async d=>{if(!await confirmAction("确认已由代理将补差实际退给客户？此操作不转账，不改变分佣。"))return false;await api("/orders/"+id(view.id)+"/cost/customer-receipt","POST",{version:c.version,evidence:d.evidence,confirmCustomerReceived:true});await refreshOpenOrder(view.id);})));return body;}
async function refreshOpenOrder(orderId){const dialog=document.querySelector('.order-detail-modal[open]');if(!dialog)return;const body=dialog.querySelector('.modal-body');const view=(await api('/orders/'+id(orderId),'GET',undefined,{fresh:true})).data;if(dialog.open&&dialog.dataset.orderId===orderId)renderOrderDetailContent(dialog,body,view);}
function openCostVerification(view){const c=view.costAccounting||{},destination=c.destination||"customer_direct";return openFormModal("核实成本 · "+view.id,[el("p",{class:"wide muted"},"只能登记真实已清算且明确关联本订单的凭证。不得填写 Session、密码、卡号或完整兑换码。历史退差基准须核实下单时约定。"),moneyField("standardUsd","退差基准 USD",c.refundBenchmarkUsd??c.standardUsd),moneyField("actualUsd","实际清算 USD",c.actualUsd??c.tradeCandidate?.usd),moneyField("feesUsd","额外真实费用 USD",c.additionalFeesUsd||"0.00"),moneyField("retainedUsd","约定保留 USD",c.retainedFeeUsd||"0.15"),input("fxRate","真实资金 USD/CNY 汇率（可选）","number",c.fxRate||"",{min:"0.000001",step:"0.000001"}),input("sourceReference","唯一清算流水标识","text",c.sourceReference||c.tradeCandidate?.reference||"",{required:true,minlength:6,maxlength:160}),select("destination","补差去向",[["customer_direct","直接退最终客户"],["platform_pass_through","退代理，由代理代退客户"]],destination),input("evidence","订单关联及清算凭证说明","textarea",c.evidence||(c.tradeCandidate?"上游订单 "+c.upstreamOrderId+" 对应卡片交易 "+c.tradeCandidate.reference+"，须核实真实清算及额外费用。":""),{required:true,minlength:6,maxlength:1000})],"确认核验并计算",async d=>{if(Number(d.actualUsd)===0&&!await confirmAction("本次实际成本为零。确认有明确零扣款凭证，而不是缺失数据？"))return false;if(!await confirmAction("确认凭证已经清算且关联本订单？退差基准按下单时约定核实，费用未重复计入。此操作只核算，不退款、不转账、不改变分佣。"))return false;await api('/orders/'+id(view.id)+'/cost','PUT',{version:c.version||0,standardUsd:d.standardUsd?Number(d.standardUsd).toFixed(2):null,actualUsd:Number(d.actualUsd).toFixed(2),feesUsd:Number(d.feesUsd).toFixed(2),retainedUsd:Number(d.retainedUsd).toFixed(2),fxRate:d.fxRate||null,sourceReference:d.sourceReference,evidence:d.evidence,destination:d.destination,confirmEvidence:true,confirmHistoricalTerms:!!c.historicalTermsMissing,confirmZeroCost:d.actualUsd!==""&&Number(d.actualUsd)===0});await refreshOpenOrder(view.id);tell("核算已保存；实际成本高于基准时无需补差，未执行付款");});}
function openCostPayment(view){const c=view.costAccounting,requestKey=key();return openFormModal("登记真实补差付款",[el("p",{class:"wide warning"},"去向："+costDestination(c.destination)+"。本操作不会转账，只登记已完成的真实付款；不能覆盖或切换已有付款去向。"),moneyField("usd","核销补差 USD",c.remainingUsd),select("currency","真实付款币种",[["USD","USD"],["CNY","CNY"]],"USD"),moneyField("amount","真实付款金额",c.remainingUsd),input("fxRate","人民币付款真实汇率（仅 CNY 必填）","number",c.fxRate||"",{step:"0.000001",min:"0.000001"}),input("method","付款方式","text","",{required:true,minlength:2,maxlength:50}),input("reference","唯一付款流水","text","",{required:true,minlength:6,maxlength:160}),input("evidence","实际付款凭证说明","textarea","",{required:true,minlength:6,maxlength:1000})],"确认已实际打款并核销",async d=>{if(!await confirmAction("确认已经向指定对象真实打款？系统只登记凭证，不代为转账，也不会减少代理分佣。"))return false;await api('/orders/'+id(view.id)+'/cost/payments','POST',{version:c.version,usd:Number(d.usd).toFixed(2),currency:d.currency,amount:Number(d.amount).toFixed(2),...(d.fxRate?{fxRate:d.fxRate}:{}),method:d.method,reference:d.reference,evidence:d.evidence,requestKey,confirmActualPayout:true});await refreshOpenOrder(view.id);tell("已登记付款；分佣账及客户原付款未变动");});}
async function costFinancePage(){const items=(await api('/finance/costs')).data||[];return [financePanelHeading(),section("成本与补差待办",el("p",{class:"muted"},"最多展示最近 200 笔已履约或已建立核算记录的订单。未核实金额不计利润；只核算、出单及登记凭证，不自动出款。"),table(["订单 / 代理","成本状态","真实 USD","毛节省 USD","净补差 USD","去向 / 状态","操作"],items.map(c=>[el("div",{},el("code",{},c.orderId),el("p",{class:"muted"},c.merchantName)),costLabel(c.status),c.actualUsd??"待核验",c.grossSavingUsd??"—",c.refundDueUsd??"—",el("div",{},costDestination(c.destination),el("p",{class:"muted"},costLabel(c.payoutState))),button("核算详情",()=>openOrderDetailModal({id:c.orderId}))])))];}
function financeMetricTiles(today){const items=[["已付订单",today.paidOrders,"paid_orders"],["平台代收单",today.platformCollectOrders,"platform_orders"],["今日收款","¥"+today.saleAmount,"receipts"],["今日净收款","¥"+today.netSaleAmount,"net_receipts"],["今日退款","¥"+today.refundedAmount,"refunds"],["履约成功",today.succeededOrders,"succeeded"],["代理佣金","¥"+today.marginAmount,"margin"],["代理采购供货","¥"+today.agentCollectSupplyAmount,"procurement"]];return statChips(items.map(([name,value,metric])=>[name,value,"查看明细",()=>openFinanceMetric(metric,today.day)]),{className:"platform-metrics"});}
function financeMetricLink(metric,day,text){return button(text,()=>openFinanceMetric(metric,day),"linkish");}
async function openFinanceMetric(metric,day){
  const titles={paid_orders:"已付订单",platform_orders:"平台代收订单",receipts:"收款明细",net_receipts:"净收款明细",refunds:"退款扣减明细",succeeded:"履约成功订单",margin:"代理佣金计算明细",procurement:"代理采购供货明细"};
  const focus=document.activeElement,controller=new AbortController(),dialog=el("dialog",{class:"workspace-modal finance-detail-modal","aria-label":titles[metric]||"资金明细"}),body=el("div",{class:"modal-body"});let busy=false;
  const read=async(page=1)=>{if(!dialog.open||busy)return;busy=true;body.setAttribute("aria-busy","true");body.replaceChildren(loadingView());try{
    const result=await api("/finance/details?day="+id(day)+"&metric="+id(metric)+"&page="+page+"&limit=20","GET",undefined,{signal:controller.signal,fresh:true});if(!dialog.open)return;
    const columns=metric==="margin"?["订单 / 代理商","付款时间","售价","供货价","普通退款","分佣计算额","已入账收益","操作"]:["订单 / 代理商","付款时间","收款","普通退款","平台退差","净收款","操作"];
    const rows=(result.data||[]).map(o=>{const open=()=>openOrderDetailModal({id:o.orderId}),identity=el("div",{},button(o.orderId,open,"linkish"),el("p",{class:"muted"},o.merchantName));
      return metric==="margin"?[identity,date(o.paidAt),"¥"+o.saleAmount,"¥"+o.supplyAmount,"¥"+o.ordinaryRefunded,"¥"+o.margin,"¥"+o.recognizedEarning,button("订单详情",open)]:[identity,date(o.paidAt),"¥"+o.saleAmount,"¥"+o.ordinaryRefunded,"¥"+o.priceAdjustmentRefunded,"¥"+o.netReceipts,button("订单详情",open)];});
    body.replaceChildren(el("p",{class:"muted"},result.basis),el("p",{},metric==="margin"?"分佣计算额 = max(售价 − 冻结供货价 − 普通退款, 0)。平台承担退差不减少基础分佣。":"净收款 = 收款 − 普通退款 − 平台退差；不是平台利润，也未扣除支付手续费。"),rows.length?table(columns,rows):el("p",{class:"empty"},"该日期没有符合条件的记录"),paginationBar(result.meta,read));
  }catch(err){if(dialog.open&&err.name!=="AbortError")body.replaceChildren(el("p",{class:"error",role:"alert"},err.message||"明细加载失败"),button("重试读取",()=>read(page)));}
  finally{busy=false;body.removeAttribute("aria-busy");}};
  dialog.append(el("div",{class:"modal-shell"},el("header",{class:"modal-head"},el("div",{},el("h2",{},titles[metric]||"资金明细"),el("p",{class:"muted"},day+" · 北京时间")),button("关闭",()=>dialog.close())),body));
  dialog.addEventListener("close",()=>{controller.abort();dialog.remove();focus?.isConnected&&focus.focus();},{once:true});document.body.append(dialog);dialog.showModal();await read();
}
`;
